sudo: true

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
      - docker build -t $TRAVIS_COMMIT .
      - docker images
      - docker tag $TRAVIS_COMMIT $DOCKER_USER/blog:$TRAVIS_BRANCH.$TRAVIS_COMMIT
      - docker push $DOCKER_USER/blog:$TRAVIS_BRANCH.$TRAVIS_COMMIT