sudo: true

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
      - docker build -t $TRAVIS_COMMIT .
    - stage: tag docker image
      - docker tag $TRAVIS_COMMIT $DOCKER_USER/blog:$TRAVIS_BRANCH.$TRAVIS_COMMIT
      - docker push $DOCKER_USER/blog:$TRAVIS_BRANCH.$TRAVIS_COMMIT
    - stage: push latest if in master
      - docker push $DOCKER_USER/blog:latest
        if: branch = master
      