#baseURL = "http://example.org/"
baseURL = "https://gomano.de" # use address of caddy container
languageCode = "en-us"
title = "gomano - go and other stuff"
theme = "massively"

[params.posts]
    foldername = "posts"
    pagesize = "6"
    featuredpost = "false"
