#baseURL = "http://example.org/"
baseURL = "http://localhost:2015" # use address of caddy container
languageCode = "en-us"
title = "My New Hugo Site"
theme = "massively"

[params.posts]
    foldername = "posts"
    pagesize = "6"
    featuredpost = "false"
